
"""initial migration

Revision ID: bf58cea9011e
Revises: 89f94e45a7a2
Create Date: 2025-03-31 18:35:49.847900+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf58cea9011e'
down_revision = '89f94e45a7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
